# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubnetCalculatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 11, 311, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.networkAddress = QtWidgets.QTextEdit(self.layoutWidget)
        self.networkAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.networkAddress.setMaximumSize(QtCore.QSize(150, 26))
        self.networkAddress.setObjectName("networkAddress")
        self.gridLayout_2.addWidget(self.networkAddress, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.hostsPerSub = QtWidgets.QTextEdit(self.layoutWidget)
        self.hostsPerSub.setMaximumSize(QtCore.QSize(150, 26))
        self.hostsPerSub.setBaseSize(QtCore.QSize(0, 1))
        self.hostsPerSub.setObjectName("hostsPerSub")
        self.gridLayout_2.addWidget(self.hostsPerSub, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.subSize = QtWidgets.QTextBrowser(self.layoutWidget)
        self.subSize.setMaximumSize(QtCore.QSize(80, 26))
        self.subSize.setObjectName("subSize")
        self.gridLayout_2.addWidget(self.subSize, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 11, 431, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 411, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.hexOctets = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.hexOctets.setMinimumSize(QtCore.QSize(0, 0))
        self.hexOctets.setMaximumSize(QtCore.QSize(300, 26))
        self.hexOctets.setObjectName("hexOctets")
        self.gridLayout.addWidget(self.hexOctets, 3, 1, 1, 1)
        self.binaryOctets = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.binaryOctets.setMinimumSize(QtCore.QSize(0, 0))
        self.binaryOctets.setMaximumSize(QtCore.QSize(300, 26))
        self.binaryOctets.setObjectName("binaryOctets")
        self.gridLayout.addWidget(self.binaryOctets, 2, 1, 1, 1)
        self.decimalAddress = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.decimalAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.decimalAddress.setMaximumSize(QtCore.QSize(300, 26))
        self.decimalAddress.setObjectName("decimalAddress")
        self.gridLayout.addWidget(self.decimalAddress, 1, 1, 1, 1)
        self.decimalOctects = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.decimalOctects.setMinimumSize(QtCore.QSize(0, 0))
        self.decimalOctects.setMaximumSize(QtCore.QSize(300, 26))
        self.decimalOctects.setObjectName("decimalOctects")
        self.gridLayout.addWidget(self.decimalOctects, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 311, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setGeometry(QtCore.QRect(5, 20, 301, 241))
        self.listWidget.setObjectName("listWidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 190, 431, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 391, 183))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 2)
        self.networkClass = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.networkClass.setMinimumSize(QtCore.QSize(0, 0))
        self.networkClass.setMaximumSize(QtCore.QSize(40, 26))
        self.networkClass.setObjectName("networkClass")
        self.gridLayout_3.addWidget(self.networkClass, 0, 2, 1, 1)
        self.numIPAddresses = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.numIPAddresses.setMinimumSize(QtCore.QSize(0, 0))
        self.numIPAddresses.setMaximumSize(QtCore.QSize(80, 26))
        self.numIPAddresses.setObjectName("numIPAddresses")
        self.gridLayout_3.addWidget(self.numIPAddresses, 2, 2, 1, 1)
        self.subnetMask = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.subnetMask.setMinimumSize(QtCore.QSize(0, 0))
        self.subnetMask.setMaximumSize(QtCore.QSize(300, 26))
        self.subnetMask.setObjectName("subnetMask")
        self.gridLayout_3.addWidget(self.subnetMask, 3, 2, 1, 2)
        self.binaryMask = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.binaryMask.setMinimumSize(QtCore.QSize(0, 0))
        self.binaryMask.setMaximumSize(QtCore.QSize(300, 26))
        self.binaryMask.setObjectName("binaryMask")
        self.gridLayout_3.addWidget(self.binaryMask, 4, 2, 1, 2)
        self.numSubnets = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.numSubnets.setMinimumSize(QtCore.QSize(0, 0))
        self.numSubnets.setMaximumSize(QtCore.QSize(60, 26))
        self.numSubnets.setObjectName("numSubnets")
        self.gridLayout_3.addWidget(self.numSubnets, 5, 2, 1, 2)
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(640, 411, 111, 31))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCalculate = QtWidgets.QAction(MainWindow)
        self.actionCalculate.setObjectName("actionCalculate")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionExit.setObjectName("actionExit")
        self.actionDiplayInfo = QtWidgets.QAction(MainWindow)
        self.actionDiplayInfo.setObjectName("actionDiplayInfo")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCalculate)
        self.menuTools.addAction(self.actionClear)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionDiplayInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Subnet Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Network Information"))
        self.label.setText(_translate("MainWindow", "Network Address: "))
        self.label_2.setText(_translate("MainWindow", "# of Hosts per Subnet:"))
        self.label_3.setText(_translate("MainWindow", "Calculated Subnet Size:  "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Address Information"))
        self.label_5.setText(_translate("MainWindow", "Decimal Address:"))
        self.label_7.setText(_translate("MainWindow", "Hex Octets:"))
        self.label_6.setText(_translate("MainWindow", "Binary Octets:"))
        self.label_4.setText(_translate("MainWindow", "Decimal Octets:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "List of IP Ranges"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Netmask Information"))
        self.label_9.setText(_translate("MainWindow", "# of IP Addresses:"))
        self.label_12.setText(_translate("MainWindow", "# of Subnets:"))
        self.label_8.setText(_translate("MainWindow", "Network Class:"))
        self.label_10.setText(_translate("MainWindow", "Subnet Mask:"))
        self.label_11.setText(_translate("MainWindow", "Binary Mask:"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionCalculate.setText(_translate("MainWindow", "Calculate"))
        self.actionCalculate.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.actionSave.setText(_translate("MainWindow", "Save As..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionDiplayInfo.setText(_translate("MainWindow", "Diplay Info"))
        self.actionDiplayInfo.setShortcut(_translate("MainWindow", "Ctrl+I"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

